import type { Player, Video, ConsularSummary, EmbassyVerification, ScoutingInquiry, DashboardStats, TeamSheet, LeagueBand, VisaEligibility, VisaType } from "./types";

export const mockPlayers: Player[] = [
  {
    id: "1",
    firstName: "Emmanuel",
    lastName: "Okonkwo",
    nationality: "Nigeria",
    dateOfBirth: "1998-03-15",
    position: "Striker",
    currentClub: "Enyimba FC",
    currentLeague: "Nigerian Professional League",
    leagueBand: 5 as LeagueBand,
    leaguePosition: 3,
    nationalTeamCaps: 12,
    nationalTeamDebut: "2021-06-15",
    internationalCaps: 12,
    continentalGames: 8,
    currentSeasonMinutes: 1850,
    totalCareerMinutes: 8500,
    height: 183,
    weight: 78,
    preferredFoot: "Right",
    medicalDataAvailable: true,
    gpsDataAvailable: true,
    schengenScore: 78,
    ukGbeScore: 72,
    usP1Score: 65,
    usO1Score: 58,
    middleEastScore: 85,
    asiaScore: 80,
    fifaTransferScore: 90,
    overallEligibilityScore: 68,
    lastUpdated: "2024-12-10",
  },
  {
    id: "2",
    firstName: "Kwame",
    lastName: "Mensah",
    nationality: "Ghana",
    dateOfBirth: "2000-07-22",
    position: "Midfielder",
    currentClub: "Accra Hearts of Oak",
    currentLeague: "Ghana Premier League",
    leagueBand: 5 as LeagueBand,
    leaguePosition: 2,
    nationalTeamCaps: 5,
    nationalTeamDebut: "2023-01-10",
    internationalCaps: 5,
    continentalGames: 4,
    currentSeasonMinutes: 920,
    totalCareerMinutes: 4200,
    medicalDataAvailable: true,
    gpsDataAvailable: false,
    schengenScore: 45,
    ukGbeScore: 42,
    usP1Score: 38,
    usO1Score: 32,
    middleEastScore: 55,
    asiaScore: 52,
    fifaTransferScore: 75,
    overallEligibilityScore: 39,
    lastUpdated: "2024-12-08",
  },
  {
    id: "3",
    firstName: "Ahmed",
    lastName: "El-Sayed",
    nationality: "Egypt",
    dateOfBirth: "1996-11-03",
    position: "Defender",
    currentClub: "Al Ahly SC",
    currentLeague: "Egyptian Premier League",
    leagueBand: 4 as LeagueBand,
    leaguePosition: 1,
    nationalTeamCaps: 28,
    nationalTeamDebut: "2019-03-20",
    internationalCaps: 28,
    continentalGames: 22,
    currentSeasonMinutes: 2340,
    totalCareerMinutes: 15800,
    height: 186,
    weight: 82,
    preferredFoot: "Left",
    medicalDataAvailable: true,
    gpsDataAvailable: true,
    schengenScore: 92,
    ukGbeScore: 88,
    usP1Score: 82,
    usO1Score: 78,
    middleEastScore: 95,
    asiaScore: 90,
    fifaTransferScore: 95,
    overallEligibilityScore: 85,
    lastUpdated: "2024-12-12",
  },
  {
    id: "4",
    firstName: "Carlos",
    lastName: "Ramirez",
    nationality: "Colombia",
    dateOfBirth: "2001-05-18",
    position: "Winger",
    currentClub: "Atletico Nacional",
    currentLeague: "Colombian Primera A",
    leagueBand: 4 as LeagueBand,
    leaguePosition: 5,
    nationalTeamCaps: 2,
    internationalCaps: 2,
    continentalGames: 6,
    currentSeasonMinutes: 650,
    totalCareerMinutes: 2100,
    medicalDataAvailable: false,
    gpsDataAvailable: false,
    schengenScore: 28,
    ukGbeScore: 25,
    usP1Score: 22,
    usO1Score: 18,
    middleEastScore: 35,
    asiaScore: 32,
    fifaTransferScore: 60,
    overallEligibilityScore: 23,
    lastUpdated: "2024-12-05",
  },
];

export const mockVideos: Video[] = [
  {
    id: "v1",
    playerId: "1",
    title: "NPFL Week 15 - Full Match Highlights",
    source: "manual",
    uploadDate: "2024-12-08",
    duration: "12:45",
    matchDate: "2024-12-07",
    competition: "NPFL",
    opponent: "Kano Pillars",
    minutesPlayed: 90,
    processed: true,
  },
  {
    id: "v2",
    playerId: "1",
    title: "CAF Champions League Group Stage",
    source: "wyscout",
    uploadDate: "2024-11-20",
    duration: "90:00",
    matchDate: "2024-11-19",
    competition: "CAF Champions League",
    opponent: "Al Ahly SC",
    minutesPlayed: 85,
    processed: true,
  },
  {
    id: "v3",
    playerId: "3",
    title: "Egyptian Super Cup Final",
    source: "veo",
    uploadDate: "2024-10-15",
    duration: "95:30",
    matchDate: "2024-10-14",
    competition: "Egyptian Super Cup",
    opponent: "Zamalek SC",
    minutesPlayed: 90,
    processed: true,
  },
];

export const mockTeamSheets: TeamSheet[] = [
  {
    id: "ts1",
    matchDate: "2024-12-07",
    homeTeam: "Enyimba FC",
    awayTeam: "Kano Pillars",
    competition: "NPFL",
    players: ["1"],
  },
  {
    id: "ts2",
    matchDate: "2024-10-14",
    homeTeam: "Al Ahly SC",
    awayTeam: "Zamalek SC",
    competition: "Egyptian Super Cup",
    players: ["3"],
  },
];

export const mockConsularSummaries: ConsularSummary[] = [
  {
    id: "cs1",
    playerId: "1",
    generatedAt: "2024-12-10T14:30:00Z",
    generatedBy: "John Smith",
    dataRangeStart: "2024-06-01",
    dataRangeEnd: "2024-12-10",
    eligibilityScore: 68,
    status: "submitted",
    embassyNotified: true,
  },
  {
    id: "cs2",
    playerId: "3",
    generatedAt: "2024-12-12T09:15:00Z",
    generatedBy: "Maria Garcia",
    dataRangeStart: "2024-06-01",
    dataRangeEnd: "2024-12-12",
    eligibilityScore: 85,
    status: "verified",
    embassyNotified: true,
  },
];

export const mockEmbassyVerifications: EmbassyVerification[] = [
  {
    id: "ev1",
    documentId: "cs1",
    playerId: "1",
    playerName: "Emmanuel Okonkwo",
    clubName: "Enyimba FC",
    submittedAt: "2024-12-10T14:35:00Z",
    status: "under_review",
    visaType: "schengen_sports" as VisaType,
    targetCountry: "Germany",
    verificationCode: "SR-2024-001",
  },
  {
    id: "ev2",
    documentId: "cs2",
    playerId: "3",
    playerName: "Ahmed El-Sayed",
    clubName: "Al Ahly SC",
    submittedAt: "2024-12-12T09:20:00Z",
    status: "approved",
    visaType: "uk_gbe" as VisaType,
    targetCountry: "United Kingdom",
    verificationCode: "SR-2024-002",
    verifiedAt: "2024-12-14T10:00:00Z",
  },
];

export const mockScoutingInquiries: ScoutingInquiry[] = [
  {
    id: "si1",
    playerId: "1",
    buyingClub: "VfL Wolfsburg",
    sellingClub: "Enyimba FC",
    status: "due_diligence",
    complianceScore: 68,
    createdAt: "2024-12-01",
    lastMessage: "Requesting additional medical documentation",
  },
  {
    id: "si2",
    playerId: "3",
    buyingClub: "Leicester City FC",
    sellingClub: "Al Ahly SC",
    status: "negotiation",
    complianceScore: 85,
    createdAt: "2024-11-28",
    lastMessage: "Terms sheet under review",
  },
];

export const mockDashboardStats: DashboardStats = {
  totalPlayers: 48,
  greenStatus: 18,
  yellowStatus: 20,
  redStatus: 10,
  pendingVerifications: 5,
  activeInquiries: 12,
  reportsGenerated: 34,
};

export const mockVisaEligibilities: Record<string, VisaEligibility[]> = {
  "1": [
    {
      visaType: "schengen_sports" as VisaType,
      visaName: "Schengen Sports Visa",
      score: 78,
      status: "green",
      breakdown: [
        { criteria: "Professional Contract", points: 20, maxPoints: 20, description: "Valid professional contract" },
        { criteria: "Match Minutes", points: 18, maxPoints: 20, description: "1850 minutes this season" },
        { criteria: "National Team Caps", points: 12, maxPoints: 15, description: "12 international caps" },
        { criteria: "Continental Experience", points: 10, maxPoints: 15, description: "8 CAF competition games" },
        { criteria: "Club Standing", points: 10, maxPoints: 15, description: "Club in 3rd position" },
        { criteria: "Age Factor", points: 8, maxPoints: 15, description: "Prime age (26)" },
      ],
      leagueBandApplied: 5 as LeagueBand,
      recommendation: "Strong candidate for Schengen sports visa approval."
    },
    {
      visaType: "uk_gbe" as VisaType,
      visaName: "UK GBE Points System",
      score: 72,
      status: "green",
      breakdown: [
        { criteria: "International Appearances", points: 12, maxPoints: 15, description: "12 senior caps" },
        { criteria: "Continental Club Competition", points: 8, maxPoints: 15, description: "CAF Champions League" },
        { criteria: "Domestic League Quality", points: 6, maxPoints: 15, description: "Band 5 - Nigeria" },
        { criteria: "Club Domestic Position", points: 12, maxPoints: 15, description: "Club finished 3rd" },
        { criteria: "Individual Performance", points: 18, maxPoints: 20, description: "Strong goal contribution" },
        { criteria: "Transfer Value", points: 16, maxPoints: 20, description: "Market value consideration" },
      ],
      leagueBandApplied: 5 as LeagueBand,
      recommendation: "Meets GBE threshold. Apply with supporting documentation."
    },
    {
      visaType: "fifa_transfer" as VisaType,
      visaName: "FIFA Transfer Rules",
      score: 90,
      status: "green",
      breakdown: [
        { criteria: "Player Registration", points: 25, maxPoints: 25, description: "Registered with NFF" },
        { criteria: "Contract Status", points: 20, maxPoints: 20, description: "Valid contract" },
        { criteria: "Training Compensation", points: 20, maxPoints: 20, description: "Training clubs documented" },
        { criteria: "Solidarity Mechanism", points: 15, maxPoints: 15, description: "Eligible clubs identified" },
        { criteria: "ITC Eligibility", points: 10, maxPoints: 10, description: "No disputes" },
        { criteria: "Protection Period", points: 0, maxPoints: 10, description: "Compensation required" },
      ],
      leagueBandApplied: 5 as LeagueBand,
      recommendation: "FIFA compliant - ready for international transfer."
    },
    {
      visaType: "middle_east" as VisaType,
      visaName: "Middle East Sports Visa",
      score: 85,
      status: "green",
      breakdown: [
        { criteria: "Professional Status", points: 25, maxPoints: 25, description: "Active professional" },
        { criteria: "Club Contract", points: 20, maxPoints: 20, description: "Valid employment" },
        { criteria: "Medical Clearance", points: 15, maxPoints: 15, description: "Medical data available" },
        { criteria: "Age Eligibility", points: 15, maxPoints: 15, description: "Within range" },
        { criteria: "Background Check", points: 10, maxPoints: 15, description: "Standard processing" },
        { criteria: "Skills Assessment", points: 0, maxPoints: 10, description: "Pending" },
      ],
      leagueBandApplied: 5 as LeagueBand,
      recommendation: "Excellent candidate for UAE/Saudi leagues."
    },
  ],
  "3": [
    {
      visaType: "schengen_sports" as VisaType,
      visaName: "Schengen Sports Visa",
      score: 92,
      status: "green",
      breakdown: [
        { criteria: "Professional Contract", points: 20, maxPoints: 20, description: "Valid professional contract" },
        { criteria: "Match Minutes", points: 20, maxPoints: 20, description: "2340 minutes this season" },
        { criteria: "National Team Caps", points: 15, maxPoints: 15, description: "28 international caps" },
        { criteria: "Continental Experience", points: 15, maxPoints: 15, description: "22 CAF competition games" },
        { criteria: "Club Standing", points: 15, maxPoints: 15, description: "Club in 1st position" },
        { criteria: "Age Factor", points: 7, maxPoints: 15, description: "Experienced (28)" },
      ],
      leagueBandApplied: 4 as LeagueBand,
      recommendation: "Excellent candidate - priority processing recommended."
    },
    {
      visaType: "uk_gbe" as VisaType,
      visaName: "UK GBE Points System",
      score: 88,
      status: "green",
      breakdown: [
        { criteria: "International Appearances", points: 15, maxPoints: 15, description: "28 senior caps" },
        { criteria: "Continental Club Competition", points: 15, maxPoints: 15, description: "CAF Champions League winner" },
        { criteria: "Domestic League Quality", points: 8, maxPoints: 15, description: "Band 4 - Egypt" },
        { criteria: "Club Domestic Position", points: 15, maxPoints: 15, description: "League champions" },
        { criteria: "Individual Performance", points: 18, maxPoints: 20, description: "Strong defensive stats" },
        { criteria: "Transfer Value", points: 17, maxPoints: 20, description: "High market value" },
      ],
      leagueBandApplied: 4 as LeagueBand,
      recommendation: "Automatic GBE approval expected."
    },
  ],
};
