name: Dependabot Auto-Merge

on:
    pull_request_target:
        types:
            - opened
            - synchronize
            - reopened

permissions:
    pull-requests: write
    contents: write

jobs:
    auto-merge:
        # Only run this on PRs from dependabot
        if: github.actor == 'dependabot[bot]'
        runs-on: ubuntu-latest
        steps:
            - name: Enable Auto-Merge for Clean PRs
              if: github.event.pull_request.mergeable_state == 'clean'
              run: |
                  gh pr merge ${{ github.event.pull_request.number }} --auto --squash
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
